#!/bin/bash

creategitignore
mkdir lib
mkdir test
echo 'require("./styles.scss");' > lib/index.js
echo 'import {assert} from "chai"' > test/index.js
createtesthtml
createindexhtml
createsetupjs
webpackconfig
createbabelrc
createeslintrc
createreadme
npm install --save-dev babel-loader babel-core
npm i -D babel-eslint
npm i -D babel-preset-stage-0
bundle
createcss 

